### ISSUE TITLE
[1.18.2] SimplePortals exporting package with same name as unrelated mod

### ISSUE THREAD

**Issue by digital-pet** [Silverminer007/simpleportals#1]
The mod appears to be exporting the package mcjty.theoneprobe.api despite not being a part of theoneprobe, which is also installed in this modpack. Log follows.

```2022-05-21 01:19:59,216 main WARN Advanced terminal features are not available in this environment
[01:19:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.fo
rgeVersion, 40.1.20, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, n
ogui]
[01:19:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.
0.2 by Eclipse Adoptium
[01:19:59] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/User/Applications/M
inecraftServer-1.18/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
Exception in thread "main" java.lang.module.ResolutionException: Modules simpleportals_reloaded and theoneprobe export p
ackage mcjty.theoneprobe.api to module create
        at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
        at java.base/java.lang.module.Resolver.finish(Unknown Source)
        at java.base/java.lang.module.Configuration.<init>(Unknown Source)
        at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler
.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingC
lassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo
nsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo
nsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149
)
```

**Comment by Jergeric** [comment]
Thanks for the post! My client didn't even get this far to produce a useful log. Removing The One Probe solved all my problems except that I needed a replacement for One Probe.... xD Would be great if the problem could be fixed soon.^^

My client just went away with the message "Minecraft Error Code - 1".

**Comment by Silverminer007** [comment]
Previously the package was exported to a compatibility fix. I have now removed this in rc2, but I am not so familiar with TheOneProbe that I could tell if there is still a requirement for a compatibility fix, so if there is please tell me
